# Generated by Django 5.0.2 on 2024-03-25 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='products',
        ),
    ]
